# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jung Youngchan
email: piggy77567@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My programming journey and other random thoughts.
twitter_username: username
github_username: queso-gato1355
minimal_mistakes_skin: dark
search: true
url: "https://queso-gato1355.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Seoul
# date_format: "%Y/%m/%d %H:%M"
breadcrumb: true

# Site verification
google-site-verification: "Kpo4IpXyJnNhq2b1kooJ_OhZqRzGqobt0_Z51vTxjfE"
naver-site-verification: "1eac99b912062c3e4fe20bfbab62cd40a48d7b07"

include:
  - _pages

enable_copy_code_button: true
repository: queso-gato1355/queso-gato1355.github.io

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-polyglot

languages: ["en", "ko"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "assets"]
parallel_localization: false

author:
  name      : "Jung Youngchan"
  avatar    : "/assets/images/bio-photo.jpg"
  bio       : "UNIST Undergraduate Student, KATUSA Rotational Unit Supply Specialist"
  location  : "Seoul, South Korea"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://queso-gato1355.github.io/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/queso-gato1355"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/%EC%98%81%EC%B0%AC-%EC%A0%95-3927923a6/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/queso-gato1355"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/%EC%98%81%EC%B0%AC-%EC%A0%95-3927923a6/"

defaults:
  # _posts (Default English)
  - scope:
      path: ""
      type: posts
    values:
      layout            : single
      author_profile    : true
      read_time         : true
      comments          : true
      share             : true
      related           : true
      show_date         : true
      lang              : "en"
      date_format       : "%B %-d, %Y, %l:%M %p"
      
  # _posts (Korean)
  - scope:
      path              : "_posts/ko"
      type              : posts
    values:
      layout            : single
      author_profile    : true
      read_time         : true
      comments          : true
      share             : true
      related           : true
      show_date         : true
      lang              : "ko"
      # permalink         : "/ko/:categories/:title/"
      date_format       : "%Y년 %m월 %d일 %H:%M"
  # _pages (English)
  - scope:
      path              : "_pages/en"
      type              : pages
    values:
      layout            : single
      author_profile    : true
      lang              : "en"
  # _pages (Korean)
  - scope:
      path              : "_pages/ko"
      type              : pages
    values:
      layout            : single
      author_profile    : true
      lang              : "ko"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

atom_feed:
  hide: true

comments:
  provider: "disqus"
  disqus:
    shortname: "queso-gato1355-github-io"

lunr:
  search_within_pages: true

analytics:
  provider: "google-gtag"
  google-gtag:
    tracking_id: "G-VQM7H6CBBV"

# For metadata, setting Twitter Open Graph tags
